services:
  db:
    image: postgres
    container_name: "db"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pgadminchoice
      POSTGRES_DB: Choice
    ports:
      - 5432:5432
    networks:
      - network
  
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: "api"
    build:
      context: ../
      dockerfile: src/WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PostgreSqlSettings__ConnectionString=User Id=root;Password=pgadminchoice;Host=db;Port=5432;Database=Choice;
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - network
  
networks:
  network:
    driver: bridge