services:
  nginx:
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/www/certbot:/var/www/certbot
    env_file:
      - .env
    environment:
      - HOST_NAME=${HOST_NAME}
      - MINIO_HOST_NAME=${MINIO_HOST_NAME}

  webapi:
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - IdentitySettings__PathToCert=/keys/signing.pfx
      - IdentitySettings__SecretKey=${SECRET_KEY}
      - IdentitySettings__CertificatePassword=${CERTIFICATE_PASSWORD}
      - IdentitySettings__Issuer=https://${HOST_NAME}
      - Clients__0__ClientId=${CLIENT_ID}
      - Clients__0__ClientSecret=${CLIENT_SECRET}
      - YandexGeocoder__ApiKey=${YANDEX_API_KEY}
      - YooKassaSettings__BaseUrl=${YOO_KASSA_BASE_URL}
      - YooKassaSettings__SecretKey=${YOO_KASSA_SECRET_KEY}
      - YooKassaSettings__AppId=${YOO_KASSA_APP_ID}
      - SmsApiSettings__Login=${SMS_API_SETTINGS_LOGIN}
      - SmsApiSettings__Password=${SMS_API_SETTINGS_PASSWORD}
      - SmsApiSettings__BaseUrl=${SMS_API_SETTINGS_BASE_URL}
      - PostgreSqlSettings__ConnectionString=${CONNECTION_STRING}
    volumes:
      - /etc/ssl/choice:/keys

  minio:
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_REDIRECT_URL=https://${MINIO_HOST_NAME}/minio/ui