services:
  nginx:
    ports:
      - 8080:80
      - 8083:443
    environment:
      - HOST_NAME=choice.ru
      - MINIO_HOST_NAME=minio.choice.ru
  
  db:
    image: postgres
    container_name: "db"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pgadminchoice
      POSTGRES_DB: Choice
    ports:
      - 5432:5432
  
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    
    environment:
      FTLCONF_webserver_api_password: 'ftl_password'
      
    restart: unless-stopped
    ports:
      - 8084:80
      - 53:53/udp
  
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - YandexGeocoder__ApiKey=${YANDEX_API_KEY}
      - YooKassaSettings__BaseUrl=${YOO_KASSA_BASE_URL}
      - YooKassaSettings__SecretKey=${YOO_KASSA_SECRET_KEY}
      - YooKassaSettings__AppId=${YOO_KASSA_APP_ID}
      - SmsApiSettings__Login=${SMS_API_SETTINGS_LOGIN}
      - SmsApiSettings__Password=${SMS_API_SETTINGS_PASSWORD}
      - SmsApiSettings__BaseUrl=${SMS_API_SETTINGS_BASE_URL}
    env_file:
      - .env
    depends_on:
      - db
  
  minio:
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123
      - MINIO_BROWSER_REDIRECT_URL=https://minio.choice.ru:8083/minio/ui
