services:
  nginx:
    ports:
      - 8080:80
      - 8081:443
  
  db:
    image: postgres
    container_name: "db"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pgadminchoice
      POSTGRES_DB: Choice
    ports:
      - 5432:5432
    
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PostgreSqlSettings__ConnectionString=User Id=root;Password=pgadminchoice;Host=db;Port=5432;Database=Choice;
      - JwtSettings__Issuer=https://choice.local:8081
    depends_on:
      - db