services:
  nginx:
    ports:
      - 80:80
      - 443:443
    volumes:
      - <path_to_cert>:/certs/localhost.crt:ro
      - <path_to_key>:/private/localhost.key:ro
    environment:
      - LISTEN_PORT=443 ssl
      - HOST_NAME=<host_name>
      - MINIO_HOST_NAME=<minio_host_name>
      - |
        SSL_DIRECTIVES=\
        ssl_certificate /certs/localhost.crt;
        ssl_certificate_key /private/localhost.key;
  
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
        
  minio:
    environment:
      - MINIO_ROOT_USER=<RootName>
      - MINIO_ROOT_PASSWORD=<Password>