services:
  nginx:
    build:
      context: ../nginx/
    container_name: nginx
    depends_on:
      - webapi
    volumes:
      - ../.docker/templates:/etc/nginx/templates
  
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: "webapi"
    build:
      context: ../
      dockerfile: src/WebApi/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+
    ports:
      - 80