services:
  nginx:
    build:
      context: ../nginx/
    container_name: nginx
    volumes:
      - /etc/ssl/choice/localhost.crt:/certs/localhost.crt:ro
      - /etc/ssl/choice/localhost.key:/private/localhost.key:ro
    depends_on:
      - api
  
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: "api"
    build:
      context: ../
      dockerfile: src/WebApi/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+;https://+
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyCertificatePassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
    volumes:
      - /etc/ssl/choice:/https:ro
    depends_on:
      - db