services:
  nginx:
    build:
      context: ../nginx/
    container_name: nginx
    depends_on:
      - webapi
      - minio
    volumes:
      - ../nginx/templates:/etc/nginx/templates
      - ../nginx/certificate.pem:/certs/certificate.pem
      - ../nginx/private_key.pem:/private/private_key.pem
  
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: "webapi"
    build:
      context: ../
      dockerfile: src/WebApi/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+
    ports:
      - 127.0.0.1:8082:80
  
  minio:
    image: quay.io/minio/minio
    container_name: "minio"
    command: server --address 0.0.0.0:80 --console-address 0.0.0.0:81 /data
    volumes:
      - ../.docker/minio/data:/data
    ports:
      - 127.0.0.1:9000:80
      - 127.0.0.1:9001:81
