<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Identity.Infrastructure</AssemblyName>
        <RootNamespace>Identity.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="MassTransit.AutofacIntegration">
        <HintPath>..\..\..\..\..\..\..\.nuget\packages\masstransit.autofac\7.3.1\lib\netstandard2.0\MassTransit.AutofacIntegration.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.EntityFrameworkCore">
        <HintPath>..\..\..\..\..\..\..\.nuget\packages\microsoft.entityframeworkcore\8.0.8\lib\net8.0\Microsoft.EntityFrameworkCore.dll</HintPath>
      </Reference>
      <Reference Include="Polly">
        <HintPath>..\..\..\..\..\..\..\.nuget\packages\polly\8.4.1\lib\net6.0\Polly.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\..\Users\IntegrationEvents\IntegrationEvents.csproj" />
      <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.8" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
    </ItemGroup>

</Project>
