<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Payments.Application</AssemblyName>
        <RootNamespace>Payments.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.35" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\Application\Application.csproj" />
      <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Dapper">
        <HintPath>..\..\..\..\..\..\..\.nuget\packages\dapper\2.1.35\lib\net7.0\Dapper.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.EntityFrameworkCore">
        <HintPath>..\..\..\..\..\..\..\.nuget\packages\microsoft.entityframeworkcore\8.0.8\lib\net8.0\Microsoft.EntityFrameworkCore.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
