version: '3.4'

services:
  nginx:
    ports:
      - "80:80"
  choice.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
  identity-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5051:80"