version: '3.4'

services:
  nginx:
    ports:
      - "80:80"
    depends_on:
      - chat
      - ordering
  chat:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8081:81"
    depends_on:
      - chat-db
      - rabbitmq
  ordering:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8080:80"
    depends_on:
      - ordering-db
      - rabbitmq
  rabbitmq:
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  ordering-db:
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  chat-db:
    environment:
      POSTGRES_PASSWORD: Pass129598