version: '3.4'

services:
  nginx:
    container_name: "nginx"
    image: nginx
    build:
      context: "../nginx/"
  client-service:
    container_name: "client-service"
    image: client-service
    build:
      context: ../
      dockerfile: services/client-service/src/ClientService.Api/Dockerfile
  chat:
    container_name: "chat"
    image: chat
    build:
      context: ../
      dockerfile: services/chat/Dockerfile
  ordering:
    container_name: "ordering"
    image: ordering
    build:
      context: ../
      dockerfile: services/ordering/src/Ordering.Api/Dockerfile
  authentication:
    container_name: "authentication"
    image: authentication
    build:
      context: ../
      dockerfile: services/authentication/Dockerfile
  rabbitmq:
    image: rabbitmq:3-management-alpine
  ordering-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
  chat-db:
    container_name: chat-db
    image: postgres
  authentication-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
  client-service-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
 
