version: '3.4'

services:
  nginx:
    ports:
      - "80:80"
    depends_on:
      - chat
      - ordering
      - authentication
      - client-service
  client-service:
    environment:
      - ASPNETCORE_URLS=http://+:8083
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8083:8083"
    depends_on:
      - rabbitmq
      - client-service-db
  chat:
    environment:
      - ASPNETCORE_URLS=http://+:8088
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8088:8088"
    depends_on:
      - chat-db
      - rabbitmq
  ordering:
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8080:8080"
    depends_on:
      - ordering-db
      - rabbitmq
  ordering-grpc:
    environment:
      - ASPNETCORE_URLS=http://+:8085
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8085:8085"
    depends_on:
      - ordering-db
  authentication:
    environment:
      - ASPNETCORE_URLS=http://+:8082
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8082:8082"
    depends_on:
      - authentication-db
  review-service:
    environment:
      - ASPNETCORE_URLS=http://+:8084
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8084:8084"
    depends_on:
      - rabbitmq
      - review-service-db
  category-service:
    environment:
      - ASPNETCORE_URLS=http://+:8086
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8086:8086"
    depends_on:
      - category-service-db
  rabbitmq:
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  ordering-db:
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  company-service:
    environment:
      - ASPNETCORE_URLS=http://+:8087
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8087:8087"
    depends_on:
      - rabbitmq
      - company-service-db
  file-service:
    environment:
      - ASPNETCORE_URLS=http://+:8089
      - ASPNETCORE_ENVIRONMENT=Development
      - FILE_UPLOAD_PATH=/etc/files
    ports:
      - 8089:8089
    volumes:
      - ~/files:/etc/files:rw
  authentication-db:
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1533:1433"
  client-service-db:
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1633:1433"
  review-service-db:
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1733:1433"
  company-service-db:
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1833:1433"
  chat-db:
    environment:
      POSTGRES_PASSWORD: Pass129598
      POSTGRES_DB: Chat
      POSTGRES_USER: root
    ports:
      - "5432:5432"
  category-service-db:
    environment:
      POSTGRES_PASSWORD: Pass129598
      POSTGRES_DB: CategoryDb
      POSTGRES_USER: root
    ports:
      - "6432:5432"