version: '3.4'

services:
  choice.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5050:80"
  identity-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5050:80"