<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Identity.Domain</AssemblyName>
        <RootNamespace>Identity.Domain</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\Domain\Domain.csproj" />
    </ItemGroup>

</Project>
