<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Chat.Infrastructure</AssemblyName>
        <RootNamespace>Chat.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\Application\Application.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\..\Users\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\..\Users\IntegrationEvents\IntegrationEvents.csproj" />
      <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FirebaseAdmin" Version="3.2.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.10" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Polly">
        <HintPath>..\..\..\..\..\..\..\.nuget\packages\polly\8.4.1\lib\net6.0\Polly.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
